monitor.alsa.rules = [
  {
    matches = [
      {
        media.class = "Audio/Sink"
        node.name = "~alsa_output\\..*(PD100X|Maono|MAONO|Podcast_Microphone).*"
      }
      {
        media.class = "Audio/Sink"
        node.description = "~.*(PD100X|Maono|MAONO|Podcast Microphone).*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 900
        priority.driver  = 900
      }
    }
  }
]
