monitor.alsa.rules = [
  {
    matches = [
      {
        media.class = "Audio/Source"
        node.name = "~alsa_input\\..*(PD100X|Maono|MAONO|Podcast_Microphone).*"
      }
      {
        media.class = "Audio/Source"
        node.description = "~.*(PD100X|Maono|MAONO|Podcast Microphone).*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 5000
        priority.driver  = 5000
      }
    }
  }
]
