monitor.alsa.rules = [
  {
    matches = [
      {
        media.class = "Audio/Sink"
        node.name = "~alsa_output\\..*(JadeAudio_JA11|FIIO_JadeAudio_JA11).*analog-stereo"
      }
    ]
    actions = {
      update-props = {
        priority.session = 3000
        priority.driver  = 3000
      }
    }
  }
  {
    matches = [
      {
        media.class = "Audio/Source"
        node.name = "~alsa_input\\..*(JadeAudio_JA11|FIIO_JadeAudio_JA11).*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 3000
        priority.driver  = 3000
      }
    }
  }
]
