monitor.alsa.rules = [
  {
    matches = [
      {
        media.class = "Audio/Sink"
        node.name = "~alsa_output\\..*hdmi.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1000
        priority.driver  = 1000
      }
    }
  }
  {
    matches = [
      {
        media.class = "Audio/Source"
        node.name = "~alsa_input\\..*hdmi.*"
      }
      {
        media.class = "Audio/Source"
        node.name = "~alsa_input\\..*monitor.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1000
        priority.driver  = 1000
      }
    }
  }
]
