" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry

set t_ZH=^[[3m
set t_ZR=^[[23m
filetype indent plugin on
autocmd BufRead,BufNewFile *.blade.php set filetype=blade
imap <C-Return> <CR><CR><C-o>k<S-s>
set clipboard+=unnamedplus
" Move lines up and down using Alt+j and Alt+k
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv


" Use <c-space> to trigger completion
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()

" COC nvim configuration

" Use <c-space> to trigger completion
if has('nvim')
  inoremap <silent><expr> <M-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif
