services:
  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - system
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2h          # every 2 hours
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2h          # every 2 hours
      timeout: 10s
      retries: 5
      start_period: 30s

  mysql:
    image: mariadb:11.8
    container_name: mysql
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - system
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 2h          # every 2 hours
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  redis_data:
  postgres_data:
  mysql_data:

networks:
  system:
    driver: bridge
