services:
  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - system
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2h          # every 2 hours
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2h          # every 2 hours
      timeout: 10s
      retries: 5
      start_period: 30s

  mysql:
    image: mariadb:11.8
    container_name: mysql
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - system
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 2h          # every 2 hours
      timeout: 10s
      retries: 3
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    environment:
      PMA_HOST: ${PMA_HOST:-mysql}
      PMA_PORT: ${PMA_PORT:-3306}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT:-300M}
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - system
    volumes:
      - /sessions

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    restart: always
    ports:
      - "${PGADMIN_PORT:-8081}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-12345678}
      PGADMIN_LISTEN_PORT: 80
      UPLOAD_LIMIT: ${UPLOAD_LIMIT:-300M}
    env_file:
      - .env
    networks:
      - system
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  redis_data:
  postgres_data:
  mysql_data:
  pgadmin_data:

networks:
  system:
    driver: bridge
