-- Generated by Wallust. Do not edit: choose a new wallpaper or run wally to regenerate it.
---@type Dotfiles.Theme
return {
  background = "rgb({{background | strip}})",
  foreground = "rgb({{foreground | strip}})",
  primary = "rgb({{color4 | strip}})",
  secondary = "rgb({{color5 | strip}})",
  primary_dim = "rgba({{color4 | strip}}80)",
}
