#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored
IMAGES_DIR="$HOME/.config/sketchybar/images" # Directory where the images are stored

FONT="Liga SFMono Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
GAP=5 # Padding right for icons and left for labels or padding between items(icon.padding_right, label.padding_left) if both exists
PADDINGS=10 # Padding for items(icon.padding_left, label.padding_right)
MARGIN=5 # Margin between items
RADIUS=8 # Corner radius for items

# Usage examples:
# background.image="$LEFT_ROUNDED"
# background.image.drawing=on
# background.color=0x00000000  # Make background transparent when using image

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=39
  color=$TRANSPARENT
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=9
  y_offset=10
  margin=10
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  #gap between icon and label
  icon.padding_right=$GAP
  label.padding_left=$GAP
  #padding for items
  icon.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  #margin between items
  background.padding_left=$MARGIN
  background.padding_right=$MARGIN

  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  background.height=30
  background.corner_radius=9
  background.drawing=on
  background.color=$BG
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/calendar.sh"
# source "$ITEM_DIR/brew.sh"
#source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/netspeed.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
